jobs:
  rendercv:
    name: RenderCV
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install RenderCV
      run: 'pip install -r requirements.txt

        '
    - name: RenderCV
      run: "cd src\ncv_file=$(find .  -maxdepth 1 -type f -name \"*_CV.yaml\" | head\
        \ -n 1)\nif [ -z \"$cv_file\" ]; then\n  echo \"No RenderCV file found!\"\n\
        \  exit 1\nfi\ncd ..\nrendercv render src/$cv_file --pdf-path ${cv_file%.yaml}.pdf\
        \ --markdown-path README.md --latex-path ${cv_file%.yaml}.tex\n"
    - name: Upload rendercv_output as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: RenderCV Output
        path: rendercv_output
    - id: changes
      uses: dorny/paths-filter@v3
      with:
        base: HEAD
        filters: "cv:\n  - '*_CV.tex'\n  - 'README.md'\n"
    - if: steps.changes.outputs.cv == 'true'
      name: Push the changes
      run: 'git config --global user.name "${{ github.actor }}"

        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git add -A

        git commit -m "render the latest CV"

        git push

        '
name: Render a CV
'on':
- workflow_dispatch
permissions: write-all
